### ISSUE TITLE
Cannot decryptMedia after update

### ISSUE THREAD

**Issue by rickricardo** [open-wa/wa-automate-nodejs#2070]
The code below always worked, but now that I updated from 4.8.2 to 4.20.4 I get the following error.
Sorry I couldnt identify what I should do to adapt to the new version.

Code:
let stickerDecryptable = await client.getStickerDecryptable(message.id);
mediaData = await decryptMedia(stickerDecryptable, uaOverride);

Error:
program.ts:290:56 - error TS2345: Argument of type 'boolean | Message' is not assignable to parameter of type 'DecryptableMessage'.
  Type 'boolean' is not assignable to type 'DecryptableMessage'.

290                         mediaData = await decryptMedia(**stickerDecryptable**, uaOverride);

**Comment by smashah** [comment]
Try this:

```javascript
let stickerDecryptable = await client.getStickerDecryptable(message.id);
if(stickerDecryptable)
mediaData = await decryptMedia(stickerDecryptable, uaOverride);
```

**Comment by rickricardo** [comment]
Code:
let stickerDecryptable = await client.getStickerDecryptable(message.id);
if(stickerDecryptable){
    mediaData = await decryptMedia(stickerDecryptable as DecryptableMessage, uaOverride);
}

Error:
program.ts:291:79 - error TS2304: Cannot find name 'DecryptableMessage'.

291                          mediaData = await decryptMedia(stickerDecryptable as **DecryptableMessage**, uaOverride);

**Comment by smashah** [comment]
@rickricardo  you will need to import DecryptableMessage from the decryption package

```javascript
import {DecryptableMessage} from '@open-wa/wa-decrypt'
```

to be honest, you probably don't even need the `as DecryptableMessage` (or use `as any` if it keeps moaning)

**Comment by rickricardo** [comment]
It worked, thanks!

**Comment by rickricardo** [comment]
After updating to 4.32.5 I now get the following error:

```
TSError: ⨯ Unable to compile TypeScript:
Program.ts:245:65 - error TS2571: Object is of type 'unknown'.

245                             console.log("TCL1: start -> error", error.response)
                                                                    ~~~~~
Program.ts:292:57 - error TS2352: Conversion of type 'boolean | Message' to type 'DecryptableMessage' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Message' is not comparable to type 'DecryptableMessage'.
    Type 'Message' is not comparable to type 'Required<Pick<{ clientUrl?: string | undefined; deprecatedMms3Url?: string | undefined; }, "deprecatedMms3Url">> & Partial<Pick<{ clientUrl?: string | undefined; deprecatedMms3Url?: string | undefined; }, "clientUrl">> & Except<...> & RequiredDecryptionMessage'.
      Type 'Message' is missing the following properties from type 'RequiredDecryptionMessage': mediaKey, size

292                          mediaData = await decryptMedia(stickerDecryptable as DecryptableMessage , uaOverride);
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by smashah** [comment]
@rickricardo please upgrade to `@open-wa/wa-decrypt` to `@open-wa/wa-decrypt@4.4.0` or use 


`mediaData = await decryptMedia(stickerDecryptable as any)`

**Comment by rickricardo** [comment]
it worked! thanks
