### ISSUE TITLE
forwardmessages not working on 4.71.0 - 4.71.10

### ISSUE THREAD

**Issue by roelbroersma** [open-wa/wa-automate-nodejs#3202]
### Are you using the latest version of the library?

- [X] I have checked and am using the latest version of the library.

### What type of session are you experiencing this issue on?

Multi-device and I have set multiDevice to true in my config OR am using the --multi-device flag

### What type of host account are you experiencing this issue on?

Business account

### Mode

EASY API/CLI

### Current Behavior

/forwardmessages is not working anymore.

To reproduce,  use Swagger or use:

curl -X 'POST' \
  'http://XXXXXXXXXXX:8004/forwardMessages' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "args": [
    "xxxxxxxxxx@g.us",
    ["false_xxxxxxxx-xxxxxxxx@g.us_xxxxxxxxxx_xxxxxxxx@c.us"],
    true
  ]
}'

{
  "success": false,
  "error": {
    "name": "Error",
    "message": "Evaluation failed: TypeError: _0xb4442a[(_0xf13f8d(...) + \"BT\")](...) is not a function\n    at window.<computed>.<computed> [as forwardMessages] (pptr://__puppeteer_evaluation_script__:1:521365)"
  }
}

At the same moment,  the terminal/cli gives:

middleware -> error Error: Evaluation failed: TypeError: _0xb4442a[(_0xf13f8d(...
) + "BT")](...) is not a function                                                
    at window.<computed>.<computed> [as forwardMessages] (pptr://__puppeteer_eval
uation_script__:1:521365)                                                        
    at ExecutionContext._ExecutionContext_evaluate (/usr/src/app/node_modules/pup
peteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:258:15)                 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/
lib/cjs/puppeteer/common/ExecutionContext.js:146:16)              

### Expected Behavior

Expected would be:

{
  "success": true
}

### Steps To Reproduce

Use swagger (see current behavior)

### DEBUG INFO

```markdown
Debug info: {                                                                  
  "WA_VERSION": "2.3000.1013182127",                                             
  "PAGE_UA": "WhatsApp/2.2147.16 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",          
  "WA_AUTOMATE_VERSION": "4.71.10",                                              
  "BROWSER_VERSION": "HeadlessChrome/124.0.6367.60",                             
  "OS": "Linux 4.4",                                                             
  "START_TS": 1714586244750,                                                     
  "RAM_INFO": "Total: 67.40 GB | Free: 47.63 GB",                                
  "PPTR_VERSION": "19.11.1"                                                      
}
```

### Environment

```markdown
- OS: Docker container, running on latest Synology DSM.
- Node: 21.7.3
- YARN_VERSION: 1.22.9
```

### Anything else?

Also happens these versions:
4.71.6
4.71.4
4.71.3
4.71.2
4.71.1
4.71.0
(other 4.71.x versions were not tested, but probably the same issue)

I also tested the /ghostforward option, that one does work.
